services:
  - type: web
    name: king-ranux-session-mega
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MEGA_EMAIL
        sync: false
      - key: MEGA_PASSWORD
        sync: false